#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."&&pwd)";EXP_ROOT="${EXP_ROOT:-/linxi/dataset/FGDD_pixels/aircraft_bbox_seed0_v1}";DATA_ROOT=/linxi/dataset/FG_SRe2L_repro/v1/datasets;RAW_ROOT=/linxi/dataset/FD2/raw/fgvc-aircraft-2013b/data;R0_ROOT=/linxi/dataset/FG_CoDA_standard/v2/baselines/random_real_standard/selected/A_imsize224/rseed0/ipc3;TEACHER=/linxi/dataset/FG_SRe2L_standard/v1/teachers/A_imsize224/tseed42/ResNet18.pth;CONTROL_ROOT=/linxi/dataset/FG_SoftAugFactorial_v2/aircraft_ipc3_v1;GPUS=(${GPUS:-0 1});EVALS_PER_GPU=${EVALS_PER_GPU:-3};mkdir -p "$EXP_ROOT"/{construction,logs,status,locks,fkd,results,post_eval,summary};ts(){ date --iso-8601=seconds; };images(){ echo "$EXP_ROOT/construction/selected/$1/ipc3"; };fkd(){ echo "$EXP_ROOT/fkd/$1/ipc3_bs20_ipc3"; }
construct(){ if [[ ! -f $EXP_ROOT/construction/construction_manifest.json ]];then python "$ROOT_DIR/CV-DD/fine_grained/prepare_aircraft_bbox_pixel_views.py" --raw-images "$RAW_ROOT/images" --boxes "$RAW_ROOT/images_box.txt" --r0-root "$R0_ROOT" --output-root "$EXP_ROOT/construction" --margin .10 >"$EXP_ROOT/logs/construction.log" 2>&1;fi;python - "$EXP_ROOT/construction/construction_manifest.json" <<'PY'
import json,sys
x=json.load(open(sys.argv[1]));assert x['status']=='complete' and x['images']==300 and x['training_gate']['passed']
PY
}
relabel_one(){ local method gpu base actual n;method=$1;gpu=$2;base="$EXP_ROOT/fkd/$method/ipc3";actual="$(fkd "$method")";n=0;[[ -d $actual ]]&&n=$(find "$actual" -name 'batch_*.tar' -type f|wc -l);if((n!=6000));then CUDA_VISIBLE_DEVICES=$gpu PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python python -u "$ROOT_DIR/CV-DD/relabel/relabel.py" --syn-data-path "$(images "$method")" --fkd-path "$base" --model-pool-dir "$(dirname "$TEACHER")" --teacher-model-name ResNet18 --gpu 0 --batch-size 20 --workers 8 --persistent-workers --dataset-name A_imsize224 --epochs 400 --seed 42 --fkd-seed 42 --full-image-resize --min-scale-crops 1 --max-scale-crops 1 --mix-type cutmix --use-fp16 --mode fkd_save >"$EXP_ROOT/logs/relabel_${method}.log" 2>&1;fi;python "$ROOT_DIR/CV-DD/fine_grained/audit_fkd.py" --fkd-dir "$actual" --images 300 --classes 100 --batch-size 20 --epochs 400 --output "$actual/fkd_audit.json">>"$EXP_ROOT/logs/relabel_${method}.log" 2>&1;}
eval_one(){ local method student gpu result log;method=$1;student=$2;gpu=$3;result="$EXP_ROOT/results/$method/ipc3_sseed$student.json";log="$EXP_ROOT/logs/eval_${method}_s$student.log";mkdir -p "$(dirname "$result")";exec 7>"$result.lock";flock -n 7||return 75;if [[ ! -f $result ]];then CUDA_VISIBLE_DEVICES=$gpu PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python -u "$ROOT_DIR/CV-DD/validate/train_fkd.py" --model ResNet18 --ipc 3 --exp-name "bbox_pixels_${method}_s$student" --original-data-path "$(images "$method")" --fkd-path "$(fkd "$method")" --output-dir "$EXP_ROOT/post_eval/$method/sseed$student" --batch-size 20 --epochs 400 --dataset-name A_imsize224 --gradient-accumulation-steps 2 --mix-type cutmix --workers 8 --persistent-workers --fkd_seed 42 --train-seed "$student" --temperature 20 --student-initialization imagenet-v1 --student-protocol-name standard_protocol_v2_bbox_pixels --adamw-weight-decay 1e-5 --adamw-beta1 .9 --adamw-beta2 .999 --adamw-eps 1e-8 --adamw-backbone-lr 1e-4 --adamw-head-lr 1e-3 --cosine-t-max 400 --cosine-eta-min 0 --val-dir "$DATA_ROOT/A_imsize224/test" --disable-wandb --per-class-output "$result">"$log" 2>&1;fi;}
main(){ exec 9>"$EXP_ROOT/locks/launcher.lock";flock -n 9||exit 75;rm -f "$EXP_ROOT/status/launcher.failed" "$EXP_ROOT/status/launcher.complete";echo "$(ts) started new_fkd=2 new_students=6">"$EXP_ROOT/status/launcher.running";construct;echo "$(ts) complete">"$EXP_ROOT/status/construction.complete";local pids=() i=0 method gpu p failed=0;for method in native_subject lowres_subject;do gpu=${GPUS[$((i%2))]};relabel_one "$method" "$gpu"&pids+=("$!");i=$((i+1));done;for p in "${pids[@]}";do wait "$p"||failed=1;done;((failed==0));echo "$(ts) complete">"$EXP_ROOT/status/relabel.complete";pids=();i=0;local student;for method in native_subject lowres_subject;do for student in 42 43 44;do gpu=${GPUS[$((i%2))]};eval_one "$method" "$student" "$gpu"&pids+=("$!");i=$((i+1));done;done;for p in "${pids[@]}";do wait "$p"||failed=1;done;((failed==0));python "$ROOT_DIR/CV-DD/fine_grained/summarize_aircraft_bbox_pixel_views.py" --root "$EXP_ROOT" --control-root "$CONTROL_ROOT">"$EXP_ROOT/logs/summary.log" 2>&1;rm -f "$EXP_ROOT/status/launcher.running";echo "$(ts) complete">"$EXP_ROOT/status/launcher.complete";}
trap 'r=$?;if((r));then rm -f "$EXP_ROOT/status/launcher.running";echo "$(ts) exit=$r">"$EXP_ROOT/status/launcher.failed";fi' EXIT
main
