#!/usr/bin/env bash
set -euo pipefail
ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}";EXP="${EXP_ROOT:-/tmp/fgdd_aircraft_six_source_loss_decomposition}";PARENT=/tmp/fgdd_aircraft_six_source_experiment;MANIFEST="$PARENT/construction/six_source_manifest.json";SOURCE_FKD=/tmp/fgdd_aircraft_six_source_stage/fkd/reference
TEACHER=/linxi/dataset/FG_SRe2L_standard/v1/teachers/A_imsize224/tseed42/ResNet18.pth;TEST=/linxi/dataset/FG_SRe2L_repro/v1/datasets/A_imsize224/test;ARMS=(object_decoded background_decoded background_hsmooth)
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1
mkdir -p "$EXP"/{logs,status,locks,fkd,results,post_eval,summary,audits};exec 9>"$EXP/locks/launcher.lock";flock -n 9||exit 75;trap 's=$?;if((s));then rm -f "$EXP/status/running";echo "$(date --iso-8601=seconds) exit=$s">"$EXP/status/failed";fi' EXIT;rm -f "$EXP/status/failed" "$EXP/status/complete";date --iso-8601=seconds>"$EXP/status/running"
rescore(){ local arm=$1 gpu=$2 out;out="$EXP/fkd/$arm";CUDA_VISIBLE_DEVICES=$gpu python -u "$ROOT/CV-DD/fine_grained/rescore_aircraft_six_source_mode.py" --manifest "$MANIFEST" --mode "$arm" --source-fkd "$SOURCE_FKD" --output-fkd "$out" --teacher "$TEACHER">"$EXP/logs/relabel_$arm.log" 2>&1;python "$ROOT/CV-DD/fine_grained/audit_aircraft_six_source_fkd.py" --manifest "$MANIFEST" --reference "$SOURCE_FKD" --compressed "$out" --output "$EXP/audits/fkd_$arm.json">"$EXP/logs/audit_$arm.log" 2>&1;}
failed=0;pids=();i=0;for arm in "${ARMS[@]}";do rescore "$arm" $((i%2))&pids+=("$!");i=$((i+1));if((${#pids[@]}==2));then for p in "${pids[@]}";do wait $p||failed=1;done;pids=();((failed==0));fi;done;for p in "${pids[@]}";do wait $p||failed=1;done;((failed==0));date --iso-8601=seconds>"$EXP/status/relabel.complete"
student(){ local arm=$1 s=$2 g=$3 result;result="$EXP/results/$arm/sseed$s.json";mkdir -p "$(dirname "$result")" "$EXP/post_eval/$arm/sseed$s";CUDA_VISIBLE_DEVICES=$g python -u "$ROOT/CV-DD/validate/train_fkd.py" --model ResNet18 --ipc 3 --exp-name "six_source_${arm}_s$s" --original-data-path "$PARENT/construction/packed" --fkd-path "$EXP/fkd/$arm" --paired-source-manifest "$MANIFEST" --paired-source-mode "$arm" --output-dir "$EXP/post_eval/$arm/sseed$s" --batch-size 20 --epochs 400 --dataset-name A_imsize224 --gradient-accumulation-steps 2 --mix-type cutmix --workers 8 --persistent-workers --fkd_seed 42 --train-seed "$s" --temperature 20 --student-initialization imagenet-v1 --student-protocol-name standard_v2_six_source_${arm} --adamw-weight-decay 1e-5 --adamw-beta1 .9 --adamw-beta2 .999 --adamw-eps 1e-8 --adamw-backbone-lr 1e-4 --adamw-head-lr 1e-3 --cosine-t-max 400 --cosine-eta-min 0 --val-dir "$TEST" --disable-wandb --per-class-output "$result">"$EXP/logs/eval_${arm}_s$s.log" 2>&1;}
pids=();i=0;for arm in "${ARMS[@]}";do for s in 42 43 44;do student "$arm" $s $((i%2))&pids+=("$!");i=$((i+1));if((${#pids[@]}==4));then for p in "${pids[@]}";do wait $p||failed=1;done;pids=();((failed==0));fi;done;done;for p in "${pids[@]}";do wait $p||failed=1;done;((failed==0));python "$ROOT/CV-DD/fine_grained/summarize_aircraft_six_source_loss_decomposition.py" --root "$EXP" --parent "$PARENT">"$EXP/logs/summary.log" 2>&1;rm -f "$EXP/status/running";date --iso-8601=seconds>"$EXP/status/complete"
