#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."&&pwd)"
EXP_ROOT="${EXP_ROOT:-/linxi/dataset/FG_TeacherHard_controls_v2/aircraft_ipc3_v1}"
DATA_ROOT="${DATA_ROOT:-/linxi/dataset/FG_SRe2L_repro/v1/datasets}"
RRC_ROOT=/linxi/dataset/FG_HardAugFactorial_v2/aircraft_ipc3_v1
FULL_ROOT=/linxi/dataset/FG_RDED_Random_fullframe_v2/aircraft_ipc3_v1
OLD_TH_ROOT=/linxi/dataset/FG_TeacherHard_RRC_v2/aircraft_ipc3_v1
SOFT_ROOT=/linxi/dataset/FG_SoftAugFactorial_v2/aircraft_ipc3_v1
RANDOM_ROOT=/linxi/dataset/FG_RandomReal_soft_v2/aircraft_v1
RDED_ROOT=/linxi/dataset/FG_RDED_original_v2/aircraft_v1
GPUS=(${GPUS:-0 1}); EVALS_PER_GPU=${EVALS_PER_GPU:-4}; PERM_SEED=20260913
mkdir -p "$EXP_ROOT"/{logs,status,locks,results,audits,summary,post_eval,permuted_fkd}
ts(){ date --iso-8601=seconds; }
source_seeds(){ [[ $1 == random_real ]]&&echo '0 1 2'||echo '42 43 44'; }
source_result(){ local method=$1 source=$2 student=${3:-42}; if [[ $method == random_real ]];then echo "$RANDOM_ROOT/results/A_imsize224/rseed$source/ipc3_sseed$student.json";else echo "$RDED_ROOT/results/A_imsize224/gseed$source/ipc3_sseed$student.json";fi; }
images(){ python - "$(source_result "$1" "$2")" <<'PY'
import json,sys;print(json.load(open(sys.argv[1]))['synthetic_data_path'])
PY
}
fkd(){ local arm=$1 method=$2 source=$3; if [[ $arm == fullframe ]];then echo "$FULL_ROOT/fkd/$method/source_seed$source/ipc3_bs20_ipc3";else echo "$RRC_ROOT/fkd/rrc_no_cutmix/$method/source_seed$source/ipc3_bs20_ipc3";fi; }
teacher_hard_result(){ local arm=$1 method=$2 source=$3 student=$4; if [[ $arm == rrc && (($method == random_real && $source == 0)||($method == original_rded && $source == 42)) ]];then echo "$OLD_TH_ROOT/results/$method/source_seed$source/ipc3_sseed$student.json";else echo "$EXP_ROOT/results/teacher_hard_$arm/$method/source_seed$source/ipc3_sseed$student.json";fi; }
audit_one(){ local arm=$1 method=$2 source=$3; python "$ROOT_DIR/CV-DD/fine_grained/audit_teacher_hard_fkd.py" --images "$(images "$method" "$source")" --fkd "$(fkd "$arm" "$method" "$source")" --output "$EXP_ROOT/audits/teacher_hard_${arm}_${method}_source${source}.json"; }
prepare_perm(){ local method source destination;method=$1;source=$2;destination="$EXP_ROOT/permuted_fkd/$method/source_seed$source/ipc3_bs20_ipc3";mkdir -p "$(dirname "$destination")";exec 8>"$destination.lock";flock -n 8||return 75;if [[ ! -f $destination/permutation_manifest.json ]];then python "$ROOT_DIR/CV-DD/fine_grained/prepare_preserved_teacher_permutation_fkd.py" --source "$(fkd rrc "$method" "$source")" --destination "$destination" --images "$(images "$method" "$source")" --seed "$PERM_SEED";fi; python "$ROOT_DIR/CV-DD/fine_grained/audit_fkd.py" --fkd-dir "$destination" --images 300 --classes 100 --batch-size 20 --epochs 400 --output "$destination/fkd_audit.json"; }
eval_teacher_hard(){ local arm=$1 method=$2 source=$3 student=$4 gpu=$5 result; result="$(teacher_hard_result "$arm" "$method" "$source" "$student")"; [[ -f $result ]]&&return 0; local log="$EXP_ROOT/logs/eval_teacher_hard_${arm}_${method}_${source}_s${student}.log"; mkdir -p "$(dirname "$result")"; CUDA_VISIBLE_DEVICES=$gpu PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python -u "$ROOT_DIR/CV-DD/validate/train_fkd.py" --model ResNet18 --ipc 3 --exp-name "teacher_hard_${arm}_${method}_${source}_s$student" --original-data-path "$(images "$method" "$source")" --fkd-path "$(fkd "$arm" "$method" "$source")" --output-dir "$EXP_ROOT/post_eval/teacher_hard_${arm}/$method/source$source/sseed$student" --batch-size 20 --epochs 400 --dataset-name A_imsize224 --gradient-accumulation-steps 2 --fkd-teacher-hard-label --workers 8 --persistent-workers --fkd_seed 42 --train-seed "$student" --temperature 20 --student-initialization imagenet-v1 --student-protocol-name standard_protocol_v2_teacher_hard --adamw-weight-decay 1e-5 --adamw-beta1 .9 --adamw-beta2 .999 --adamw-eps 1e-8 --adamw-backbone-lr 1e-4 --adamw-head-lr 1e-3 --cosine-t-max 400 --cosine-eta-min 0 --val-dir "$DATA_ROOT/A_imsize224/test" --disable-wandb --per-class-output "$result" >"$log" 2>&1; }
eval_permuted(){ local method source student gpu result log;method=$1;source=$2;student=$3;gpu=$4;result="$EXP_ROOT/results/preserved_permutation/$method/source_seed$source/ipc3_sseed$student.json";log="$EXP_ROOT/logs/eval_perm_${method}_${source}_s${student}.log";mkdir -p "$(dirname "$result")";exec 7>"$result.lock";flock -n 7||return 75;[[ -f $result ]]&&return 0;CUDA_VISIBLE_DEVICES=$gpu PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python -u "$ROOT_DIR/CV-DD/validate/train_fkd.py" --model ResNet18 --ipc 3 --exp-name "preserved_perm_rrc_${method}_${source}_s$student" --original-data-path "$(images "$method" "$source")" --fkd-path "$EXP_ROOT/permuted_fkd/$method/source_seed$source/ipc3_bs20_ipc3" --output-dir "$EXP_ROOT/post_eval/preserved_permutation/$method/source$source/sseed$student" --batch-size 20 --epochs 400 --dataset-name A_imsize224 --gradient-accumulation-steps 2 --workers 8 --persistent-workers --fkd_seed 42 --train-seed "$student" --temperature 20 --student-initialization imagenet-v1 --student-protocol-name standard_protocol_v2_preserved_nontarget_permutation --adamw-weight-decay 1e-5 --adamw-beta1 .9 --adamw-beta2 .999 --adamw-eps 1e-8 --adamw-backbone-lr 1e-4 --adamw-head-lr 1e-3 --cosine-t-max 400 --cosine-eta-min 0 --val-dir "$DATA_ROOT/A_imsize224/test" --disable-wandb --per-class-output "$result" >"$log" 2>&1; }
run_pool(){ local -a jobs=("$@"); local pids=() i=0 job gpu p failed=0; for job in "${jobs[@]}";do gpu=${GPUS[$((i%2))]}; eval "$job $gpu"&pids+=("$!");i=$((i+1));if((${#pids[@]}==2*EVALS_PER_GPU));then for p in "${pids[@]}";do wait "$p"||failed=1;done;((failed==0))||return 1;pids=();fi;done;for p in "${pids[@]}";do wait "$p"||failed=1;done;((failed==0)); }
main(){ exec 9>"$EXP_ROOT/locks/launcher.lock";flock -n 9||exit 75;rm -f "$EXP_ROOT/status/launcher.failed" "$EXP_ROOT/status/launcher.complete";echo "$(ts) started new_student_runs=48 teacher_queries=0">"$EXP_ROOT/status/launcher.running"
 local prep=() method source;for method in random_real original_rded;do for source in $(source_seeds "$method");do prep+=("audit_one rrc $method $source >/dev/null" "audit_one fullframe $method $source >/dev/null" "prepare_perm $method $source >/dev/null");done;done;run_pool "${prep[@]}";echo "$(ts) complete">"$EXP_ROOT/status/preparation.complete"
 local jobs=() student;for method in random_real original_rded;do for source in $(source_seeds "$method");do for student in 42 43 44;do if ! [[ ($method == random_real && $source == 0)||($method == original_rded && $source == 42) ]];then jobs+=("eval_teacher_hard rrc $method $source $student");fi;jobs+=("eval_teacher_hard fullframe $method $source $student" "eval_permuted $method $source $student");done;done;done;run_pool "${jobs[@]}"
 python "$ROOT_DIR/CV-DD/fine_grained/summarize_aircraft_teacher_hard_controls.py" --root "$EXP_ROOT" --old-teacher-hard-root "$OLD_TH_ROOT" --soft-root "$SOFT_ROOT" --hard-root "$RRC_ROOT">"$EXP_ROOT/logs/summary.log" 2>&1;rm -f "$EXP_ROOT/status/launcher.running";echo "$(ts) complete">"$EXP_ROOT/status/launcher.complete"; }
trap 'r=$?;if((r));then rm -f "$EXP_ROOT/status/launcher.running";echo "$(ts) exit=$r">"$EXP_ROOT/status/launcher.failed";fi' EXIT
main
