#!/usr/bin/env bash
set -euo pipefail
ROOT="${REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}";EXP="${EXP_ROOT:-/tmp/fgdd_aircraft_six_source_seed_completion}";STAGE="${STAGE_ROOT:-/tmp/fgdd_aircraft_six_source_seed_completion_stage}";PARENT=/tmp/fgdd_aircraft_six_source_experiment;EXT=/tmp/fgdd_aircraft_six_source_extensions
TEACHER=/linxi/dataset/FG_SRe2L_standard/v1/teachers/A_imsize224/tseed42/ResNet18.pth;TEST=/linxi/dataset/FG_SRe2L_repro/v1/datasets/A_imsize224/test;WEIGHTS=/linxi/models/torchvision/resnet18-f37072fd.pth;R0_BASE=/linxi/dataset/FG_CoDA_standard/v2/baselines/random_real_standard/selected/A_imsize224;R0_SEED0=/linxi/dataset/FG_HardLabel_standard/v1/aircraft_ipc3_rc_rrc_regions_v1/results/mild_rc/r0
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1
mkdir -p "$EXP"/{logs,status,locks,results,checkpoints,post_eval,summary,audits} "$STAGE";exec 9>"$EXP/locks/launcher.lock";flock -n 9||exit 75;trap 's=$?;if((s));then rm -f "$EXP/status/running";echo "$(date --iso-8601=seconds) exit=$s">"$EXP/status/failed";fi' EXIT;rm -f "$EXP/status/failed" "$EXP/status/complete";date --iso-8601=seconds>"$EXP/status/running"
relabel(){ local r=$1 g=$2 m="$EXT/construction/rseed$r/six_source_manifest.json" out="$STAGE/rseed$r";if [[ ! -f $out/reference/relabel_manifest.json ]];then CUDA_VISIBLE_DEVICES=$g python -u "$ROOT/CV-DD/fine_grained/relabel_aircraft_six_source.py" --manifest "$m" --reference-fkd "$out/reference" --compressed-fkd "$out/compressed" --teacher "$TEACHER" --epochs 400 --batch-size 20 --workers 8 --seed 42>"$EXP/logs/relabel_rseed$r.log" 2>&1;fi;python "$ROOT/CV-DD/fine_grained/audit_aircraft_six_source_fkd.py" --manifest "$m" --reference "$out/reference" --compressed "$out/compressed" --output "$EXP/audits/fkd_rseed$r.json">"$EXP/logs/audit_rseed$r.log" 2>&1;}
relabel 1 0&p0=$!;relabel 2 1&p1=$!;failed=0;wait $p0||failed=1;wait $p1||failed=1;((failed==0));date --iso-8601=seconds>"$EXP/status/relabel.complete"
hard_r0(){ local r=$1 s=$2 g=$3 result="$EXP/results/hard_r0/rseed$r/sseed$s.json";mkdir -p "$(dirname "$result")" "$EXP/checkpoints/hard_r0/rseed$r/sseed$s";CUDA_VISIBLE_DEVICES=$g python -u "$ROOT/CV-DD/validate/train_hard_label_v1.py" --train-dir "$R0_BASE/rseed$r/ipc3" --val-dir "$TEST" --dataset-name A_imsize224 --num-classes 100 --ipc 3 --student-seed "$s" --result "$result" --checkpoint-dir "$EXP/checkpoints/hard_r0/rseed$r/sseed$s" --imagenet-weights-path "$WEIGHTS" --total-updates 3000 --batch-size 64 --backbone-lr 3e-4 --head-lr 3e-3 --backbone-min-lr 0 --head-min-lr 0 --momentum .9 --weight-decay 5e-4 --eval-every-updates 300 --workers 8 --persistent-workers --val-batch-size 256 --protocol-name hard_label_v1_mild_rc --train-crop-mode mild_rc>"$EXP/logs/hard_r0_r${r}_s$s.log" 2>&1;}
soft(){ local r=$1 mode=$2 s=$3 g=$4 result="$EXP/results/soft/rseed$r/$mode/sseed$s.json" manifest="$EXT/construction/rseed$r/six_source_manifest.json";mkdir -p "$(dirname "$result")" "$EXP/post_eval/soft/rseed$r/$mode/sseed$s";CUDA_VISIBLE_DEVICES=$g python -u "$ROOT/CV-DD/validate/train_fkd.py" --model ResNet18 --ipc 3 --exp-name "six_source_r${r}_${mode}_s$s" --original-data-path "$EXT/construction/rseed$r/packed" --fkd-path "$STAGE/rseed$r/$mode" --paired-source-manifest "$manifest" --paired-source-mode "$mode" --output-dir "$EXP/post_eval/soft/rseed$r/$mode/sseed$s" --batch-size 20 --epochs 400 --dataset-name A_imsize224 --gradient-accumulation-steps 2 --mix-type cutmix --workers 8 --persistent-workers --fkd_seed 42 --train-seed "$s" --temperature 20 --student-initialization imagenet-v1 --student-protocol-name standard_v2_six_source_fullframe_${mode}_r${r} --adamw-weight-decay 1e-5 --adamw-beta1 .9 --adamw-beta2 .999 --adamw-eps 1e-8 --adamw-backbone-lr 1e-4 --adamw-head-lr 1e-3 --cosine-t-max 400 --cosine-eta-min 0 --val-dir "$TEST" --disable-wandb --per-class-output "$result">"$EXP/logs/soft_r${r}_${mode}_s$s.log" 2>&1;}
pids=();i=0
for r in 1 2;do for s in 42 43 44;do hard_r0 $r $s $((i%2))&pids+=("$!");i=$((i+1));if((${#pids[@]}==4));then for p in "${pids[@]}";do wait $p||failed=1;done;pids=();((failed==0));fi;done;done
for r in 1 2;do for mode in reference compressed;do for s in 42 43 44;do soft $r $mode $s $((i%2))&pids+=("$!");i=$((i+1));if((${#pids[@]}==4));then for p in "${pids[@]}";do wait $p||failed=1;done;pids=();((failed==0));fi;done;done;done
for p in "${pids[@]}";do wait $p||failed=1;done;((failed==0));python "$ROOT/CV-DD/fine_grained/summarize_aircraft_six_source_seed_completion.py" --root "$EXP" --parent "$PARENT" --extensions "$EXT" --r0-seed0 "$R0_SEED0">"$EXP/logs/summary.log" 2>&1;rm -f "$EXP/status/running";date --iso-8601=seconds>"$EXP/status/complete"
