#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."&&pwd)";EXP_ROOT="${EXP_ROOT:-/linxi/dataset/FG_SoftAugFactorial_v2/aircraft_ipc3_v1}";DATA_ROOT="${DATA_ROOT:-/linxi/dataset/FG_SRe2L_repro/v1/datasets}";TEACHER_DIR="${TEACHER_DIR:-/linxi/dataset/FG_SRe2L_standard/v1/teachers/A_imsize224/tseed42}"
HARD_ROOT=/linxi/dataset/FG_HardAugFactorial_v2/aircraft_ipc3_v1;RANDOM_ROOT=/linxi/dataset/FG_RandomReal_soft_v2/aircraft_v1;RDED_ROOT=/linxi/dataset/FG_RDED_original_v2/aircraft_v1;OFFOFF=/linxi/dataset/FG_RDED_Random_fullframe_v2/aircraft_ipc3_v1;ONON=/linxi/dataset/FG_HardReplay_standard/v2/aircraft_v1
GPUS=(${GPUS:-0 1});EVALS_PER_GPU=${EVALS_PER_GPU:-4};LOG_ROOT="$EXP_ROOT/logs";STATUS_ROOT="$EXP_ROOT/status";LOCK_ROOT="$EXP_ROOT/locks";mkdir -p "$LOG_ROOT" "$STATUS_ROOT" "$LOCK_ROOT" "$EXP_ROOT/summary"
ts(){ date --iso-8601=seconds;};wait_all(){ local f=0 p;for p in "$@";do wait "$p"||f=1;done;((f==0));};srcres(){ if [[ $1 == random_real ]];then echo "$RANDOM_ROOT/results/A_imsize224/rseed${2}/ipc3_sseed${3}.json";else echo "$RDED_ROOT/results/A_imsize224/gseed${2}/ipc3_sseed${3}.json";fi;};fkd(){ echo "$HARD_ROOT/fkd/${1}/${2}/source_seed${3}/ipc3_bs20_ipc3";}
eval_one(){ local arm=$1 method=$2 src=$3 student=$4 gpu=$5 source="$(srcres "$method" "$src" "$student")" result="$EXP_ROOT/results/$arm/$method/source_seed$src/ipc3_sseed$student.json" log="$LOG_ROOT/eval_${arm}_${method}_${src}_s$student.log" mix=()
 [[ $arm == fullframe_cutmix ]]&&mix=(--mix-type cutmix);mkdir -p "$(dirname "$result")";exec 7>"$result.lock";flock -n 7||return 75
 local images;images=$(python - "$source" <<'PY'
import json,sys;print(json.load(open(sys.argv[1]))['synthetic_data_path'])
PY
 )
 if [[ ! -f $result ]];then CUDA_VISIBLE_DEVICES=$gpu PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python -u "$ROOT_DIR/CV-DD/validate/train_fkd.py" --model ResNet18 --ipc 3 --exp-name "soft_${arm}_${method}_${src}_s$student" --original-data-path "$images" --fkd-path "$(fkd "$arm" "$method" "$src")" --output-dir "$EXP_ROOT/post_eval" --batch-size 20 --epochs 400 --dataset-name A_imsize224 --gradient-accumulation-steps 2 "${mix[@]}" --workers 8 --persistent-workers --fkd_seed 42 --train-seed "$student" --temperature 20 --student-initialization imagenet-v1 --student-protocol-name standard_protocol_v2 --adamw-weight-decay 1e-5 --adamw-beta1 .9 --adamw-beta2 .999 --adamw-eps 1e-8 --adamw-backbone-lr 1e-4 --adamw-head-lr 1e-3 --cosine-t-max 400 --cosine-eta-min 0 --val-dir "$DATA_ROOT/A_imsize224/test" --disable-wandb --per-class-output "$result" >"$log" 2>&1;fi
 python "$ROOT_DIR/CV-DD/fine_grained/record_aircraft_soft_aug_factorial.py" --result "$result" --source-image-result "$source" --fkd "$(fkd "$arm" "$method" "$src")" --teacher "$TEACHER_DIR/ResNet18.pth" --method "$method" --source-seed "$src" --student-seed "$student" --arm "$arm" >>"$log" 2>&1;}
main(){exec 9>"$LOCK_ROOT/launcher.lock";flock -n 9||exit 75;rm -f "$STATUS_ROOT/launcher.failed" "$STATUS_ROOT/launcher.complete";echo "$(ts) started expected=36 reused_fkd=12">"$STATUS_ROOT/launcher.running";local pids=() idx=0 arm method src student gpu
 for arm in rrc_no_cutmix fullframe_cutmix;do for method in random_real original_rded;do [[ $method == random_real ]]&&seeds=(0 1 2)||seeds=(42 43 44);for src in "${seeds[@]}";do for student in 42 43 44;do gpu=${GPUS[$((idx%2))]};eval_one "$arm" "$method" "$src" "$student" "$gpu"&pids+=("$!");idx=$((idx+1));if((${#pids[@]}==2*EVALS_PER_GPU));then wait_all "${pids[@]}";pids=();fi;done;done;done;done;if((${#pids[@]}));then wait_all "${pids[@]}";fi
 python "$ROOT_DIR/CV-DD/fine_grained/summarize_aircraft_soft_aug_factorial.py" --root "$EXP_ROOT" --offoff-root "$OFFOFF" --onon-root "$ONON" --hard-middle-root "$HARD_ROOT">"$LOG_ROOT/summary.log" 2>&1;rm -f "$STATUS_ROOT/launcher.running";echo "$(ts) complete">"$STATUS_ROOT/launcher.complete";}
trap 'r=$?;if((r));then rm -f "$STATUS_ROOT/launcher.running";echo "$(ts) exit=$r">"$STATUS_ROOT/launcher.failed";fi' EXIT
main
