#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."&&pwd)";EXP_ROOT="${EXP_ROOT:-/linxi/dataset/FG_RDED_tile_soft_v2/aircraft_ipc3_v1}";DATA_ROOT="${DATA_ROOT:-/linxi/dataset/FG_SRe2L_repro/v1/datasets}";TEACHER_DIR="${TEACHER_DIR:-/linxi/dataset/FG_SRe2L_standard/v1/teachers/A_imsize224/tseed42}";CONTROL_ROOT=/linxi/dataset/FG_SoftAugFactorial_v2/aircraft_ipc3_v1;RDED_ROOT=/linxi/dataset/FG_RDED_original_v2/aircraft_v1
GPUS=(${GPUS:-0 1});EVALS_PER_GPU=${EVALS_PER_GPU:-4};LOG_ROOT="$EXP_ROOT/logs";STATUS_ROOT="$EXP_ROOT/status";LOCK_ROOT="$EXP_ROOT/locks";mkdir -p "$LOG_ROOT" "$STATUS_ROOT" "$LOCK_ROOT" "$EXP_ROOT/summary" "$EXP_ROOT/audits"
ts(){ date --iso-8601=seconds;};wait_all(){ local f=0 p;for p in "$@";do wait "$p"||f=1;done;((f==0));};images(){ echo "$RDED_ROOT/generated/A_imsize224/gseed$1/ipc3";};fkd(){ echo "$EXP_ROOT/fkd/gseed${1}/ipc3_bs20_ipc3";};genmanifest(){ echo "$RDED_ROOT/generated/A_imsize224/gseed$1/generation_manifest.json";};control(){ echo "$CONTROL_ROOT/results/fullframe_cutmix/original_rded/source_seed${1}/ipc3_sseed${2}.json";}
relabel_one(){ local g=$1 gpu=$2 base="$EXP_ROOT/fkd/gseed$g/ipc3" actual="$(fkd "$g")" n=0;[[ -d $actual ]]&&n=$(find "$actual" -name 'batch_*.tar' -type f|wc -l)
 if ((n!=6000));then CUDA_VISIBLE_DEVICES=$gpu PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python python -u "$ROOT_DIR/CV-DD/relabel/relabel.py" --syn-data-path "$(images "$g")" --fkd-path "$base" --model-pool-dir "$TEACHER_DIR" --teacher-model-name ResNet18 --gpu 0 --batch-size 20 --workers 8 --dataset-name A_imsize224 --epochs 400 --seed 42 --fkd-seed 42 --single-quadrant --quadrant-seed 42 --quadrant-schedule random_permutation --full-image-resize --min-scale-crops 1 --max-scale-crops 1 --mix-type cutmix --use-fp16 --mode fkd_save >"$LOG_ROOT/relabel_gseed$g.log" 2>&1;fi
 python "$ROOT_DIR/CV-DD/fine_grained/audit_fkd.py" --fkd-dir "$actual" --images 300 --classes 100 --batch-size 20 --epochs 400 >>"$LOG_ROOT/relabel_gseed$g.log" 2>&1
 python "$ROOT_DIR/CV-DD/fine_grained/audit_quadrant_fkd.py" --fkd-dir "$actual" --image-root "$(images "$g")" --epochs 400 --batch-size 20 --seed 42 --schedule random_permutation --output "$actual/quadrant_audit.json" >>"$LOG_ROOT/relabel_gseed$g.log" 2>&1
 python "$ROOT_DIR/CV-DD/fine_grained/audit_rded_tile_sources.py" --generation-manifest "$(genmanifest "$g")" --output "$EXP_ROOT/audits/source_gseed$g.json" >>"$LOG_ROOT/relabel_gseed$g.log" 2>&1;}
eval_one(){ local g=$1 s=$2 gpu=$3 result="$EXP_ROOT/results/gseed$g/ipc3_sseed$s.json" log="$LOG_ROOT/eval_gseed${g}_s$s.log";mkdir -p "$(dirname "$result")";exec 7>"$result.lock";flock -n 7||return 75
 if [[ ! -f $result ]];then CUDA_VISIBLE_DEVICES=$gpu PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 python -u "$ROOT_DIR/CV-DD/validate/train_fkd.py" --model ResNet18 --ipc 3 --exp-name "rded_tile_soft_v2_g${g}_s$s" --original-data-path "$(images "$g")" --fkd-path "$(fkd "$g")" --output-dir "$EXP_ROOT/post_eval" --batch-size 20 --epochs 400 --dataset-name A_imsize224 --gradient-accumulation-steps 2 --mix-type cutmix --workers 8 --persistent-workers --fkd_seed 42 --train-seed "$s" --temperature 20 --student-initialization imagenet-v1 --student-protocol-name standard_protocol_v2 --adamw-weight-decay 1e-5 --adamw-beta1 .9 --adamw-beta2 .999 --adamw-eps 1e-8 --adamw-backbone-lr 1e-4 --adamw-head-lr 1e-3 --cosine-t-max 400 --cosine-eta-min 0 --val-dir "$DATA_ROOT/A_imsize224/test" --disable-wandb --per-class-output "$result" >"$log" 2>&1;fi
 python "$ROOT_DIR/CV-DD/fine_grained/record_rded_tile_soft_v2.py" --result "$result" --control-result "$(control "$g" "$s")" --fkd "$(fkd "$g")" --teacher "$TEACHER_DIR/ResNet18.pth" --quadrant-audit "$(fkd "$g")/quadrant_audit.json" --source-audit "$EXP_ROOT/audits/source_gseed$g.json" --generation-seed "$g" --student-seed "$s" >>"$log" 2>&1;}
main(){ exec 9>"$LOCK_ROOT/launcher.lock";flock -n 9||exit 75;rm -f "$STATUS_ROOT/launcher.failed" "$STATUS_ROOT/launcher.complete";echo "$(ts) started expected=9">"$STATUS_ROOT/launcher.running";local pids=() i=0 g gpu s
 for g in 42 43 44;do gpu=${GPUS[$((i%2))]};relabel_one "$g" "$gpu"&pids+=("$!");i=$((i+1));if((${#pids[@]}==2));then wait_all "${pids[@]}";pids=();fi;done;if((${#pids[@]}));then wait_all "${pids[@]}";fi;echo "$(ts) complete">"$STATUS_ROOT/relabel.complete"
 pids=();i=0;for g in 42 43 44;do for s in 42 43 44;do gpu=${GPUS[$((i%2))]};eval_one "$g" "$s" "$gpu"&pids+=("$!");i=$((i+1));if((${#pids[@]}==2*EVALS_PER_GPU));then wait_all "${pids[@]}";pids=();fi;done;done;if((${#pids[@]}));then wait_all "${pids[@]}";fi
 python "$ROOT_DIR/CV-DD/fine_grained/summarize_rded_tile_soft_v2.py" --root "$EXP_ROOT">"$LOG_ROOT/summary.log" 2>&1;rm -f "$STATUS_ROOT/launcher.running";echo "$(ts) complete">"$STATUS_ROOT/launcher.complete";}
trap 'r=$?;if((r));then rm -f "$STATUS_ROOT/launcher.running";echo "$(ts) exit=$r">"$STATUS_ROOT/launcher.failed";fi' EXIT
main
